package dev.perxenic.groovyengine.datagen.generator;

import dev.perxenic.groovyengine.GroovyEngine;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class DatapackGenerator {

    // This path is now relative to the root pack generated by GroovyEnginePackRootGenerator
    private static final Path DATA_ROOT = GroovyEnginePackRootGenerator.DATAPACK_ROOT.getRoot().resolve("data")
            .resolve(GroovyEngine.MODID); // Your mod ID as the namespace

    public static void generate() {
        try {
            Files.createDirectories(DATA_ROOT.resolve("advancement"));
            // Files.createDirectories(DATA_ROOT.resolve("banner_pattern"));
            // Files.createDirectories(DATA_ROOT.resolve("cat_variant"));
            // Files.createDirectories(DATA_ROOT.resolve("chat_type"));
            // Files.createDirectories(DATA_ROOT.resolve("chicken_variant"));
            // Files.createDirectories(DATA_ROOT.resolve("cow_variant"));
            // Files.createDirectories(DATA_ROOT.resolve("damage_type"));
            // Files.createDirectories(DATA_ROOT.resolve("dialog"));
            // Files.createDirectories(DATA_ROOT.resolve("dimension"));
            // Files.createDirectories(DATA_ROOT.resolve("dimension_type"));
            // Files.createDirectories(DATA_ROOT.resolve("enchantment"));
            // Files.createDirectories(DATA_ROOT.resolve("enchantment_provider"));
            // Files.createDirectories(DATA_ROOT.resolve("frog_variant"));
            // Files.createDirectories(DATA_ROOT.resolve("instrument"));
            // Files.createDirectories(DATA_ROOT.resolve("item_modifier"));
            // Files.createDirectories(DATA_ROOT.resolve("jukebox_song"));
            Files.createDirectories(DATA_ROOT.resolve("loot_table"));
            // Files.createDirectories(DATA_ROOT.resolve("painting_variant"));
            // Files.createDirectories(DATA_ROOT.resolve("pig_variant"));
            // Files.createDirectories(DATA_ROOT.resolve("predicate"));
            Files.createDirectories(DATA_ROOT.resolve("recipe"));
            // Files.createDirectories(DATA_ROOT.resolve("test_environment"));
            // Files.createDirectories(DATA_ROOT.resolve("test_instance"));
            // Files.createDirectories(DATA_ROOT.resolve("trial_spawner"));
            // Files.createDirectories(DATA_ROOT.resolve("trim_material"));
            // Files.createDirectories(DATA_ROOT.resolve("trim_pattern"));

            Files.createDirectories(DATA_ROOT.resolve("tags/function"));
            // Files.createDirectories(DATA_ROOT.resolve("tags/block"));
            // Files.createDirectories(DATA_ROOT.resolve("tags/item"));

            GroovyEngine.LOGGER.info("Generated Datapack data folder structure.");

        } catch (IOException e) {
            GroovyEngine.LOGGER.error("Failed to generate Datapack data structure: {}", e.getMessage());
        }
    }
}